# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  pull_request: 
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    environment: github-pages

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Initiate new build
        run: echo New build initiated...
        
      # Runs a set of commands using the runners shell
      - name: Install dependencies 
        run: |
          npm ci
          echo Dependencies installed successfully!

      - name: Load environment variables
        uses: xom9ikk/dotenv@v2.2.0
        with:
          path: ./
          mode: production
          load-mode: strict
      
      - name: Verify environment variables
        run: |
          echo Variable 1: ${{ env.REACT_APP_HOST_URL }}
          echo Variable 2: ${{ env.REACT_APP_WEBSITE_TITLE }}
          echo Variable 3: ${{ env.REACT_APP_WEBSITE_DESCRIPTION }}
    
      - name: Create new build
        env:
          REACT_APP_HOST_URL: ${{ env.REACT_APP_HOST_URL }}
          REACT_APP_WEBSITE_TITLE: ${{ env.REACT_APP_WEBSITE_TITLE }}
          REACT_APP_WEBSITE_DESCRIPTION: ${{ env.REACT_APP_WEBSITE_DESCRIPTION }}
        run: |
          npm run build
          echo Build created successfully!
          
      - name: Build success
        run: echo Latest build created successfully!
