# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: github-pages

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Initiate new build
        run: echo New build initiated...
        
      # Runs a set of commands using the runners shell
      - name: Install dependencies 
        run: |
          yarn install
          echo Dependencies installed successfully!

      - name: Create new build
        run: |
          yarn run build
          echo Build created successfully!

      - name: Deploy latest build
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master-build
          publish_dir: ./build
          
      - name: Deployment success
        run: echo Latest build deployed successfully!
